[2023-12-04T12:11:42.156+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder_test manual__2023-12-04T04:11:01.651527+00:00 [queued]>
[2023-12-04T12:11:42.184+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder_test manual__2023-12-04T04:11:01.651527+00:00 [queued]>
[2023-12-04T12:11:42.188+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-04T12:11:42.231+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): delete_file_in_actual_folder_test> on 2023-12-04 04:11:01.651527+00:00
[2023-12-04T12:11:42.235+0800] {standard_task_runner.py:57} INFO - Started process 24226 to run task
[2023-12-04T12:11:42.243+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'delete_file_in_actual_folder_test', 'manual__2023-12-04T04:11:01.651527+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpn72qrqdi']
[2023-12-04T12:11:42.246+0800] {standard_task_runner.py:85} INFO - Job 134: Subtask delete_file_in_actual_folder_test
[2023-12-04T12:11:42.320+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder_test manual__2023-12-04T04:11:01.651527+00:00 [running]> on host azfartitu.
[2023-12-04T12:11:42.433+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='delete_file_in_actual_folder_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T04:11:01.651527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T04:11:01.651527+00:00'
[2023-12-04T12:11:42.445+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 98, in delete_file_in_actual_folder_test
    formatted_current_date = formatted_current_dates[0]
TypeError: 'NoneType' object is not subscriptable
[2023-12-04T12:11:42.452+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=delete_file_in_actual_folder_test, execution_date=20231204T041101, start_date=20231204T041142, end_date=20231204T041142
[2023-12-04T12:11:42.474+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 134 for task delete_file_in_actual_folder_test ('NoneType' object is not subscriptable; 24226)
[2023-12-04T12:11:42.497+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T12:11:42.531+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
