[2023-11-30T07:50:43.893+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T23:50:29.949209+00:00 [queued]>
[2023-11-30T07:50:43.905+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T23:50:29.949209+00:00 [queued]>
[2023-11-30T07:50:43.906+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T07:50:43.945+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): delete_file_in_actual_folder> on 2023-11-29 23:50:29.949209+00:00
[2023-11-30T07:50:43.950+0800] {standard_task_runner.py:57} INFO - Started process 29714 to run task
[2023-11-30T07:50:43.953+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'delete_file_in_actual_folder', 'manual__2023-11-29T23:50:29.949209+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmphtrr0ng_']
[2023-11-30T07:50:43.954+0800] {standard_task_runner.py:85} INFO - Job 59: Subtask delete_file_in_actual_folder
[2023-11-30T07:50:44.001+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T23:50:29.949209+00:00 [running]> on host azfartitu.
[2023-11-30T07:50:44.077+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='delete_file_in_actual_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T23:50:29.949209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T23:50:29.949209+00:00'
[2023-11-30T07:50:44.084+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T07:50:44.612+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T07:50:45.660+0800] {wasb.py:504} INFO - Deleted blobs: ('current_season_history/28112023/current_season_history_28112023.json',)
[2023-11-30T07:50:45.661+0800] {logging_mixin.py:154} INFO - File is deleted
[2023-11-30T07:50:45.662+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 80, in delete_file_in_actual_folder
    adls_hook = AzureDataLakeStorageV2Hook(conn_id=adls_conn_id)
TypeError: AzureDataLakeStorageV2Hook.__init__() got an unexpected keyword argument 'conn_id'
[2023-11-30T07:50:45.670+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=delete_file_in_actual_folder, execution_date=20231129T235029, start_date=20231129T235043, end_date=20231129T235045
[2023-11-30T07:50:45.699+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task delete_file_in_actual_folder (AzureDataLakeStorageV2Hook.__init__() got an unexpected keyword argument 'conn_id'; 29714)
[2023-11-30T07:50:45.736+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T07:50:45.750+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
