[2023-11-30T22:19:25.804+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-30T14:19:18.220078+00:00 [queued]>
[2023-11-30T22:19:25.816+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-30T14:19:18.220078+00:00 [queued]>
[2023-11-30T22:19:25.816+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T22:19:25.842+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): move_file_into_archive_folder> on 2023-11-30 14:19:18.220078+00:00
[2023-11-30T22:19:25.848+0800] {standard_task_runner.py:57} INFO - Started process 47267 to run task
[2023-11-30T22:19:25.855+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'move_file_into_archive_folder', 'manual__2023-11-30T14:19:18.220078+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmp9nmnecu4']
[2023-11-30T22:19:25.858+0800] {standard_task_runner.py:85} INFO - Job 79: Subtask move_file_into_archive_folder
[2023-11-30T22:19:25.917+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-30T14:19:18.220078+00:00 [running]> on host azfartitu.
[2023-11-30T22:19:26.014+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='move_file_into_archive_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T14:19:18.220078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T14:19:18.220078+00:00'
[2023-11-30T22:19:26.077+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 46, in move_file_into_archive_folder
    list_of_files = az_hook.get_blobs_list(container_name=container_name) #To get the first level blob name
UnboundLocalError: local variable 'container_name' referenced before assignment
[2023-11-30T22:19:26.084+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=move_file_into_archive_folder, execution_date=20231130T141918, start_date=20231130T141925, end_date=20231130T141926
[2023-11-30T22:19:26.105+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task move_file_into_archive_folder (local variable 'container_name' referenced before assignment; 47267)
[2023-11-30T22:19:26.147+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T22:19:26.183+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
