[2023-11-30T06:29:51.786+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:29:26.183686+00:00 [queued]>
[2023-11-30T06:29:51.793+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:29:26.183686+00:00 [queued]>
[2023-11-30T06:29:51.793+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T06:29:51.813+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): delete_file_in_actual_folder> on 2023-11-29 22:29:26.183686+00:00
[2023-11-30T06:29:51.819+0800] {standard_task_runner.py:57} INFO - Started process 27657 to run task
[2023-11-30T06:29:51.822+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'delete_file_in_actual_folder', 'manual__2023-11-29T22:29:26.183686+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpjzbtkcgd']
[2023-11-30T06:29:51.823+0800] {standard_task_runner.py:85} INFO - Job 50: Subtask delete_file_in_actual_folder
[2023-11-30T06:29:51.866+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:29:26.183686+00:00 [running]> on host azfartitu.
[2023-11-30T06:29:51.943+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='delete_file_in_actual_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T22:29:26.183686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T22:29:26.183686+00:00'
[2023-11-30T06:29:51.949+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T06:29:52.382+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T06:29:53.481+0800] {wasb.py:504} INFO - Deleted blobs: ('current_season_history/28112023/current_season_history_28112023.json',)
[2023-11-30T06:29:53.482+0800] {logging_mixin.py:154} INFO - File is deleted
[2023-11-30T06:29:54.550+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 79, in delete_file_in_actual_folder
    blob_service_client.get_blob_client(container=container_name, blob=blob.name).delete_blob()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 1211, in delete_blob
    process_storage_error(error)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 1209, in delete_blob
    self._client.blob.delete(**options)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 2116, in delete
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 165, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: This operation is not permitted on a non-empty directory.
RequestId:d2fbc704-801e-0019-0913-239270000000
Time:2023-11-29T22:29:54.3865373Z
ErrorCode:DirectoryIsNotEmpty
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>DirectoryIsNotEmpty</Code><Message>This operation is not permitted on a non-empty directory.
RequestId:d2fbc704-801e-0019-0913-239270000000
Time:2023-11-29T22:29:54.3865373Z</Message></Error>
[2023-11-30T06:29:54.556+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=delete_file_in_actual_folder, execution_date=20231129T222926, start_date=20231129T222951, end_date=20231129T222954
[2023-11-30T06:29:54.576+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task delete_file_in_actual_folder (This operation is not permitted on a non-empty directory.
RequestId:d2fbc704-801e-0019-0913-239270000000
Time:2023-11-29T22:29:54.3865373Z
ErrorCode:DirectoryIsNotEmpty
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>DirectoryIsNotEmpty</Code><Message>This operation is not permitted on a non-empty directory.
RequestId:d2fbc704-801e-0019-0913-239270000000
Time:2023-11-29T22:29:54.3865373Z</Message></Error>; 27657)
[2023-11-30T06:29:54.610+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T06:29:54.635+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
