[2023-12-08T00:20:33.007+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-12-07T16:20:29.158129+00:00 [queued]>
[2023-12-08T00:20:33.015+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-12-07T16:20:29.158129+00:00 [queued]>
[2023-12-08T00:20:33.015+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-08T00:20:33.037+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_file_from_blob_test> on 2023-12-07 16:20:29.158129+00:00
[2023-12-08T00:20:33.040+0800] {standard_task_runner.py:57} INFO - Started process 59218 to run task
[2023-12-08T00:20:33.045+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'download_file_from_blob_test', 'manual__2023-12-07T16:20:29.158129+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpxx3194op']
[2023-12-08T00:20:33.047+0800] {standard_task_runner.py:85} INFO - Job 160: Subtask download_file_from_blob_test
[2023-12-08T00:20:33.091+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-12-07T16:20:29.158129+00:00 [running]> on host azfartitu.
[2023-12-08T00:20:33.170+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='download_file_from_blob_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-07T16:20:29.158129+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-07T16:20:29.158129+00:00'
[2023-12-08T00:20:33.183+0800] {logging_mixin.py:154} INFO - Temporary directory created: /tmp/tmpjzsyzgdz
[2023-12-08T00:20:33.191+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-08T00:20:33.647+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-08T00:20:40.997+0800] {logging_mixin.py:154} INFO - File is downloaded at /tmp/tmpjzsyzgdz
[2023-12-08T00:20:41.292+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-08T00:20:41.297+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-08T00:20:42.930+0800] {logging_mixin.py:154} INFO - File is uploaded at blob, silver container
[2023-12-08T00:20:42.931+0800] {logging_mixin.py:154} INFO - File is deleted in /tmp/tmpjzsyzgdz
[2023-12-08T00:20:42.931+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 75, in download_file_from_blob_test
    os.rmdir(temp_dir)
OSError: [Errno 39] Directory not empty: '/tmp/tmpjzsyzgdz'
[2023-12-08T00:20:42.934+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=download_file_from_blob_test, execution_date=20231207T162029, start_date=20231207T162033, end_date=20231207T162042
[2023-12-08T00:20:42.951+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 160 for task download_file_from_blob_test ([Errno 39] Directory not empty: '/tmp/tmpjzsyzgdz'; 59218)
[2023-12-08T00:20:42.971+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T00:20:42.983+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
