[2023-11-24T12:56:24.371+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league.download_file_from_blob manual__2023-11-24T04:56:05.572172+00:00 [queued]>
[2023-11-24T12:56:24.383+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league.download_file_from_blob manual__2023-11-24T04:56:05.572172+00:00 [queued]>
[2023-11-24T12:56:24.384+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-24T12:56:24.407+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_file_from_blob> on 2023-11-24 04:56:05.572172+00:00
[2023-11-24T12:56:24.414+0800] {standard_task_runner.py:57} INFO - Started process 79997 to run task
[2023-11-24T12:56:24.429+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league', 'download_file_from_blob', 'manual__2023-11-24T04:56:05.572172+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/fantasy_premier_league_dag.py', '--cfg-path', '/tmp/tmp456xcezm']
[2023-11-24T12:56:24.432+0800] {standard_task_runner.py:85} INFO - Job 31: Subtask download_file_from_blob
[2023-11-24T12:56:24.494+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league.download_file_from_blob manual__2023-11-24T04:56:05.572172+00:00 [running]> on host azfartitu.
[2023-11-24T12:56:24.605+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league' AIRFLOW_CTX_TASK_ID='download_file_from_blob' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T04:56:05.572172+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T04:56:05.572172+00:00'
[2023-11-24T12:56:24.631+0800] {logging_mixin.py:154} INFO - Temporary directory created: /tmp/tmpqqwfay9j
[2023-11-24T12:56:24.639+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-24T12:56:25.281+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/fantasy_premier_league_dag.py", line 98, in get_file_from_blob
    az_hook.get_file(file_path=temp_file_path, container_name='bronze', blob_name=blob_name)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 390, in get_file
    with open(file_path, "wb") as fileblob:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqqwfay9j/player_metadata/24112023/player_metadata_24112023.json'
[2023-11-24T12:56:25.285+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league, task_id=download_file_from_blob, execution_date=20231124T045605, start_date=20231124T045624, end_date=20231124T045625
[2023-11-24T12:56:25.305+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task download_file_from_blob ([Errno 2] No such file or directory: '/tmp/tmpqqwfay9j/player_metadata/24112023/player_metadata_24112023.json'; 79997)
[2023-11-24T12:56:25.331+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T12:56:25.343+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
