[2023-11-24T17:57:01.350+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-11-24T09:56:58.389929+00:00 [queued]>
[2023-11-24T17:57:01.367+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-11-24T09:56:58.389929+00:00 [queued]>
[2023-11-24T17:57:01.368+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-24T17:57:01.417+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_file_from_blob_test> on 2023-11-24 09:56:58.389929+00:00
[2023-11-24T17:57:01.423+0800] {standard_task_runner.py:57} INFO - Started process 99502 to run task
[2023-11-24T17:57:01.430+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'download_file_from_blob_test', 'manual__2023-11-24T09:56:58.389929+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpve9ttwc0']
[2023-11-24T17:57:01.438+0800] {standard_task_runner.py:85} INFO - Job 6: Subtask download_file_from_blob_test
[2023-11-24T17:57:01.555+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.download_file_from_blob_test manual__2023-11-24T09:56:58.389929+00:00 [running]> on host azfartitu.
[2023-11-24T17:57:01.812+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='download_file_from_blob_test' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T09:56:58.389929+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T09:56:58.389929+00:00'
[2023-11-24T17:57:01.833+0800] {logging_mixin.py:154} INFO - Temporary directory created: /tmp/tmpwk5atm2q
[2023-11-24T17:57:01.840+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-24T17:57:03.770+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-24T17:57:06.352+0800] {logging_mixin.py:154} INFO - File is downloaded at /tmp/tmpwk5atm2q
[2023-11-24T17:57:06.498+0800] {logging_mixin.py:154} INFO - <class 'list'>
[2023-11-24T17:57:06.499+0800] {logging_mixin.py:154} INFO - File is deleted in /tmp/tmpwk5atm2q
[2023-11-24T17:57:06.842+0800] {logging_mixin.py:154} INFO - /tmp/tmpwk5atm2q/100_24112023.json is created
[2023-11-24T17:57:06.846+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-24T17:57:06.852+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-24T17:57:07.843+0800] {logging_mixin.py:154} INFO - File is uploaded at blob
[2023-11-24T17:57:07.844+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 87, in download_file_from_blob_test
    os.rmdir(temp_dir)
OSError: [Errno 39] Directory not empty: '/tmp/tmpwk5atm2q'
[2023-11-24T17:57:07.849+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=download_file_from_blob_test, execution_date=20231124T095658, start_date=20231124T095701, end_date=20231124T095707
[2023-11-24T17:57:07.871+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task download_file_from_blob_test ([Errno 39] Directory not empty: '/tmp/tmpwk5atm2q'; 99502)
[2023-11-24T17:57:07.926+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T17:57:07.939+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
