[2023-12-01T08:09:45.644+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder scheduled__2023-11-30T00:09:35.188071+00:00 [queued]>
[2023-12-01T08:09:45.664+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder scheduled__2023-11-30T00:09:35.188071+00:00 [queued]>
[2023-12-01T08:09:45.664+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-01T08:09:45.774+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): move_file_into_archive_folder> on 2023-11-30 00:09:35.188071+00:00
[2023-12-01T08:09:45.802+0800] {standard_task_runner.py:57} INFO - Started process 50272 to run task
[2023-12-01T08:09:45.810+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'move_file_into_archive_folder', 'scheduled__2023-11-30T00:09:35.188071+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmp20soh2au']
[2023-12-01T08:09:45.813+0800] {standard_task_runner.py:85} INFO - Job 93: Subtask move_file_into_archive_folder
[2023-12-01T08:09:45.903+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder scheduled__2023-11-30T00:09:35.188071+00:00 [running]> on host azfartitu.
[2023-12-01T08:09:46.027+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='move_file_into_archive_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T00:09:35.188071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T00:09:35.188071+00:00'
[2023-12-01T08:09:46.042+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 58, in move_file_into_archive_folder
    formatted_current_date = formatted_current_dates[0]
IndexError: list index out of range
[2023-12-01T08:09:46.048+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=move_file_into_archive_folder, execution_date=20231130T000935, start_date=20231201T000945, end_date=20231201T000946
[2023-12-01T08:09:46.070+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task move_file_into_archive_folder (list index out of range; 50272)
[2023-12-01T08:09:46.104+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T08:09:46.128+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
