[2023-11-30T06:26:42.288+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:26:25.546394+00:00 [queued]>
[2023-11-30T06:26:42.299+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:26:25.546394+00:00 [queued]>
[2023-11-30T06:26:42.299+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T06:26:42.318+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): delete_file_in_actual_folder> on 2023-11-29 22:26:25.546394+00:00
[2023-11-30T06:26:42.322+0800] {standard_task_runner.py:57} INFO - Started process 27500 to run task
[2023-11-30T06:26:42.332+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'delete_file_in_actual_folder', 'manual__2023-11-29T22:26:25.546394+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmphitkrwl4']
[2023-11-30T06:26:42.333+0800] {standard_task_runner.py:85} INFO - Job 45: Subtask delete_file_in_actual_folder
[2023-11-30T06:26:42.376+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.delete_file_in_actual_folder manual__2023-11-29T22:26:25.546394+00:00 [running]> on host azfartitu.
[2023-11-30T06:26:42.448+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='delete_file_in_actual_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T22:26:25.546394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T22:26:25.546394+00:00'
[2023-11-30T06:26:42.454+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T06:26:43.072+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-11-30T06:26:44.117+0800] {wasb.py:504} INFO - Deleted blobs: ('current_season_history/28112023/current_season_history_28112023.json',)
[2023-11-30T06:26:44.118+0800] {logging_mixin.py:154} INFO - File is deleted
[2023-11-30T06:26:44.118+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 75, in delete_file_in_actual_folder
    blob_service_client = BlobServiceClient.from_connection_string(connectionAZURE_BLOB_CONN_ID)
NameError: name 'connectionAZURE_BLOB_CONN_ID' is not defined
[2023-11-30T06:26:44.127+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=delete_file_in_actual_folder, execution_date=20231129T222625, start_date=20231129T222642, end_date=20231129T222644
[2023-11-30T06:26:44.151+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task delete_file_in_actual_folder (name 'connectionAZURE_BLOB_CONN_ID' is not defined; 27500)
[2023-11-30T06:26:44.196+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T06:26:44.213+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
