[2023-12-22T15:51:07.179+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test scheduled__2023-12-21T07:50:34.065040+00:00 [queued]>
[2023-12-22T15:51:07.189+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test scheduled__2023-12-21T07:50:34.065040+00:00 [queued]>
[2023-12-22T15:51:07.189+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-22T15:51:07.220+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_old_date_test> on 2023-12-21 07:50:34.065040+00:00
[2023-12-22T15:51:07.225+0800] {standard_task_runner.py:57} INFO - Started process 106958 to run task
[2023-12-22T15:51:07.228+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'get_old_date_test', 'scheduled__2023-12-21T07:50:34.065040+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpyrby4cpj']
[2023-12-22T15:51:07.230+0800] {standard_task_runner.py:85} INFO - Job 211: Subtask get_old_date_test
[2023-12-22T15:51:07.269+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.get_old_date_test scheduled__2023-12-21T07:50:34.065040+00:00 [running]> on host azfartitu.
[2023-12-22T15:51:07.385+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='get_old_date_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T07:50:34.065040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-21T07:50:34.065040+00:00'
[2023-12-22T15:51:07.442+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-22T15:51:09.138+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 48, in get_old_date_test
    min_date = min(datetime_dates)
ValueError: min() arg is an empty sequence
[2023-12-22T15:51:09.151+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=get_old_date_test, execution_date=20231221T075034, start_date=20231222T075107, end_date=20231222T075109
[2023-12-22T15:51:09.181+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 211 for task get_old_date_test (min() arg is an empty sequence; 106958)
[2023-12-22T15:51:09.211+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-22T15:51:09.238+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
