[2023-12-12T15:24:28.086+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league.get_old_date scheduled__2023-12-11T07:20:02.453019+00:00 [queued]>
[2023-12-12T15:24:28.095+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league.get_old_date scheduled__2023-12-11T07:20:02.453019+00:00 [queued]>
[2023-12-12T15:24:28.096+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T15:24:28.117+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_old_date> on 2023-12-11 07:20:02.453019+00:00
[2023-12-12T15:24:28.119+0800] {standard_task_runner.py:57} INFO - Started process 123255 to run task
[2023-12-12T15:24:28.143+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league', 'get_old_date', 'scheduled__2023-12-11T07:20:02.453019+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/fantasy_premier_league_dag.py', '--cfg-path', '/tmp/tmpfu067yam']
[2023-12-12T15:24:28.144+0800] {standard_task_runner.py:85} INFO - Job 196: Subtask get_old_date
[2023-12-12T15:24:28.178+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league.get_old_date scheduled__2023-12-11T07:20:02.453019+00:00 [running]> on host azfartitu.
[2023-12-12T15:24:28.247+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league' AIRFLOW_CTX_TASK_ID='get_old_date' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T07:20:02.453019+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T07:20:02.453019+00:00'
[2023-12-12T15:24:28.254+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-12T15:24:29.882+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/fantasy_premier_league_dag.py", line 168, in get_old_date
    min_date = min(datetime_dates)
ValueError: min() arg is an empty sequence
[2023-12-12T15:24:29.887+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league, task_id=get_old_date, execution_date=20231211T072002, start_date=20231212T072428, end_date=20231212T072429
[2023-12-12T15:24:29.907+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 196 for task get_old_date (min() arg is an empty sequence; 123255)
[2023-12-12T15:24:29.949+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T15:24:29.970+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
