[2023-12-04T11:46:19.778+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-04T03:46:14.607337+00:00 [queued]>
[2023-12-04T11:46:19.792+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-04T03:46:14.607337+00:00 [queued]>
[2023-12-04T11:46:19.792+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-04T11:46:19.820+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_old_date_test> on 2023-12-04 03:46:14.607337+00:00
[2023-12-04T11:46:19.823+0800] {standard_task_runner.py:57} INFO - Started process 19048 to run task
[2023-12-04T11:46:19.828+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'get_old_date_test', 'manual__2023-12-04T03:46:14.607337+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpker0l67e']
[2023-12-04T11:46:19.830+0800] {standard_task_runner.py:85} INFO - Job 127: Subtask get_old_date_test
[2023-12-04T11:46:19.914+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-04T03:46:14.607337+00:00 [running]> on host azfartitu.
[2023-12-04T11:46:20.065+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='get_old_date_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T03:46:14.607337+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T03:46:14.607337+00:00'
[2023-12-04T11:46:20.114+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-04T11:48:20.947+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 40, in get_old_date_test
    list_of_files = az_hook.get_blobs_list_recursive(container_name=container_name) #To get the first level blob name
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 322, in get_blobs_list_recursive
    for blob in blobs:
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_list_blobs_helper.py", line 93, in _get_next_cb
    return self._command(
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 2588, in list_blob_flat_segment
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 549, in send
    raise err
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 523, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 312, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 119, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 336, in send
    return self._transport.send(request, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 381, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7fb83d6b1690>: Failed to resolve 'azfarsadev.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)
[2023-12-04T11:48:20.984+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=get_old_date_test, execution_date=20231204T034614, start_date=20231204T034619, end_date=20231204T034820
[2023-12-04T11:48:21.016+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 127 for task get_old_date_test (<urllib3.connection.HTTPSConnection object at 0x7fb83d6b1690>: Failed to resolve 'azfarsadev.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution); 19048)
[2023-12-04T11:48:21.028+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T11:48:21.087+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
