[2023-12-22T16:10:39.810+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_silver_file_into_archive_folder_test manual__2023-12-22T08:10:31.429351+00:00 [queued]>
[2023-12-22T16:10:39.818+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_silver_file_into_archive_folder_test manual__2023-12-22T08:10:31.429351+00:00 [queued]>
[2023-12-22T16:10:39.818+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-22T16:10:39.842+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): move_silver_file_into_archive_folder_test> on 2023-12-22 08:10:31.429351+00:00
[2023-12-22T16:10:39.845+0800] {standard_task_runner.py:57} INFO - Started process 109080 to run task
[2023-12-22T16:10:39.849+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'move_silver_file_into_archive_folder_test', 'manual__2023-12-22T08:10:31.429351+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpvr90b4cw']
[2023-12-22T16:10:39.851+0800] {standard_task_runner.py:85} INFO - Job 220: Subtask move_silver_file_into_archive_folder_test
[2023-12-22T16:10:39.889+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.move_silver_file_into_archive_folder_test manual__2023-12-22T08:10:31.429351+00:00 [running]> on host azfartitu.
[2023-12-22T16:10:39.960+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='move_silver_file_into_archive_folder_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T08:10:31.429351+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T08:10:31.429351+00:00'
[2023-12-22T16:10:39.966+0800] {logging_mixin.py:154} INFO - value 11122023
[2023-12-22T16:10:39.974+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-22T16:10:40.986+0800] {logging_mixin.py:154} INFO - File is renamed
[2023-12-22T16:10:40.986+0800] {logging_mixin.py:154} INFO - ['current_season_history', 'player_metadata', 'position_metadata', 'teams_metadata']
[2023-12-22T16:10:40.986+0800] {logging_mixin.py:154} INFO - current_season_history
[2023-12-22T16:10:40.988+0800] {logging_mixin.py:154} INFO - Created local temporary folder
[2023-12-22T16:10:40.989+0800] {logging_mixin.py:154} INFO - current_season_history/current/11122023/current_season_history_11122023.json
[2023-12-22T16:10:40.992+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-22T16:10:41.841+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 84, in move_silver_file_into_archive_folder_test
    az_hook.get_file(file_path=temp_file_path, container_name=container_name, blob_name=blob_path)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 391, in get_file
    stream = self.download(container_name=container_name, blob_name=blob_name, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 446, in download
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 942, in download_blob
    return StorageStreamDownloader(**options)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 366, in __init__
    self._response = self._initial_request()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 462, in _initial_request
    process_storage_error(error)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 414, in _initial_request
    location_mode, response = self._clients.blob.download(
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1611, in download
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 165, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
RequestId:66d7c589-c01e-006a-3dae-34cae3000000
Time:2023-12-22T08:10:39.1066817Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:66d7c589-c01e-006a-3dae-34cae3000000
Time:2023-12-22T08:10:39.1066817Z</Message></Error>
[2023-12-22T16:10:41.852+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=move_silver_file_into_archive_folder_test, execution_date=20231222T081031, start_date=20231222T081039, end_date=20231222T081041
[2023-12-22T16:10:41.870+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 220 for task move_silver_file_into_archive_folder_test (The specified blob does not exist.
RequestId:66d7c589-c01e-006a-3dae-34cae3000000
Time:2023-12-22T08:10:39.1066817Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:66d7c589-c01e-006a-3dae-34cae3000000
Time:2023-12-22T08:10:39.1066817Z</Message></Error>; 109080)
[2023-12-22T16:10:41.911+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-22T16:10:41.925+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
